### ISSUE TITLE
Read configuration from .yml file which passed -config <configfile.yml> as command line

### ISSUE THREAD

**Issue by vsysoev** [fuzzing-stuff/nats2tg#2]
Nats2tg is configured by config.yml file which has following structure:

```YAML
nats:
  server: <url-to-nats server>
telegram:
 url: <url for telegramm to connect>
 token: <token to connect>
routes:
  -:
    topic: "<topic name>"
    channel: "<channel id>"
 ```
